server {
    listen 7001;
    listen [::]:7001;
    server_name _;
    root /var/www/kolbb-wiki;
    index index.html;
    charset utf-8;
    autoindex off;

    access_log /var/log/nginx/kolbb-wiki.access.log;
    error_log /var/log/nginx/kolbb-wiki.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
